version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t masssh/othellon-app .
      - run:
          command: docker build -t masssh/othellon-app -f ./app/Dockerfile ./app
      - run: docker push masssh/othellon-app:$CIRCLE_BRANCH
